### ISSUE TITLE
tmpfs mounted with "noexec" prevents loading junixsocket native library from classpath; Docker container issue

### ISSUE THREAD

**Issue by FilGor** [kohlschutter/junixsocket#136]
**Describe the bug**
Nothing happens after the line 86. Stepping into with debugger ends up with no result / output.
<img width="750" alt="image" src="https://github.com/kohlschutter/junixsocket/assets/80070678/e82c6e19-8062-4c52-bc47-4557e0d4da59">

1.  run java application (.jar) inside the docker container, that creates a socket using junixsocket.
2. container parameters
```
        userns_mode: 'host'
        tty: true
        privileged: true
        stdin_open: true
        security_opt:
            - seccomp=unconfined
        cgroup_parent: docker.slice
        cgroup: host
        tmpfs:
            - /run
            - /run/lock
            - /tmp
                 restart: always
        networks:
            network-network:
                ipv4_address: 182.28.4.2
        ports:
            - "8091:8080"
            - "5010:5006"
        extra_hosts:
            - "host.docker.internal:host-gateway"
```

**Expected behavior**
Socket file should be created.

**Output/Screenshots**
Nothing is printed out to the standard output.

**Please make sure to test the problem still occurs on the latest version of junixsocket**
Version 2.6.2 - latest on maven repository

The selftest is available from the [Release section](https://github.com/kohlschutter/junixsocket/releases) on GitHub.

All minor version updates (e.g., 2.4.x -> 2.5.x) are supposed to be backwards compatible.
If you find that this isn't the case, please mention it in your report. Thank you!

**Notes**
Add any other context about the problem here. Please link/attach any source code that is useful to diagnose the issue.
